### ISSUE TITLE
[SUGGESTION] Ability to change football map and edit football map

### ISSUE THREAD

**Issue by DogeisCut** [Salama/bonk-host#1]
I think this would be a neat feature however maps would have to be created for it, maybe add football to the editor dropdown too?

**Comment by Salama** [comment]
Looks like football map can't be modified visually without everyone having mods, which would mean invisible walls etc. The best football modification I could do is swapping team spawns.
If you want that feature, it should be its own mod.

**Comment by Salama** [comment]
Also probably doable with [Game Mode Maker](https://github.com/SneezingCactus/gmmaker)
